from collections.abc import Callable
from typing import Any, Final, final

__all__: Final = [
    "WebView",
    "PageLoadEvent",
    "NewWindowResponse",
    "DragDropEvent",
    "pump_events",
    "ensure_gtk_init",
    "disable_macos_automatic_window_tabbing",
    "disable_macos_window_tabbing",
]

@final
class PageLoadEvent:
    Started: PageLoadEvent
    Finished: PageLoadEvent

@final
class NewWindowResponse:
    Allow: NewWindowResponse
    Deny: NewWindowResponse

@final
class DragDropEvent:
    Enter: DragDropEvent
    Over: DragDropEvent
    Drop: DragDropEvent
    Leave: DragDropEvent
    Unknown: DragDropEvent

@final
class WebView:
    def __new__(
        cls,
        parent: int,
        *,
        owner_thread: int | None = None,
        width: int = 800,
        height: int = 600,
        url: str | None = None,
        html: str | None = None,
        visible: bool = True,
        devtools: bool = False,
        focused: bool = True,
        background_color: tuple[int, int, int, int] | None = None,
        user_agent: str | None = None,
        initialization_script: str | None = None,
        on_navigation: Callable[[str], bool] | None = None,
        on_new_window: Callable[[str], NewWindowResponse] | None = None,
        page_load_listening: bool = False,
        ipc_listening: bool = False,
        title_listening: bool = False,
        drag_drop_listening: bool = False,
    ) -> WebView: ...
    def load_url(self, url: str) -> None: ...
    def load_html(self, html: str) -> None: ...
    def reload(self) -> None: ...
    def eval_js(self, script: str) -> None: ...
    def eval_js_with_callback(
        self, script: str, callback: Callable[[str], Any]
    ) -> int: ...
    def drain_eval_callbacks(
        self,
    ) -> list[tuple[int, Callable[[str], Any], str | None]]: ...
    def drain_sync_hooks(self) -> None: ...
    def take_queue_drop_counts(self) -> tuple[int, int, int, int, int]: ...
    def set_ipc_listening(self, enabled: bool) -> None: ...
    def set_on_navigation(self, handler: Callable[[str], bool]) -> None: ...
    def clear_on_navigation(self) -> None: ...
    def set_page_load_listening(self, enabled: bool) -> None: ...
    def drain_page_load_events(self) -> list[tuple[PageLoadEvent, str]]: ...
    def drain_ipc_messages(self) -> list[str]: ...
    def drain_title_events(self) -> list[str]: ...
    def drain_drag_drop_events(
        self,
    ) -> list[tuple[DragDropEvent, list[str], tuple[int, int]]]: ...
    def _enqueue_ipc_message(self, message: str) -> None: ...
    def _enqueue_title_event(self, title: str) -> None: ...
    def _enqueue_drag_drop_event(
        self,
        event: DragDropEvent,
        paths: list[str],
        position: tuple[int, int],
    ) -> None: ...
    def set_title_listening(self, enabled: bool) -> None: ...
    def set_on_new_window(
        self, handler: Callable[[str], NewWindowResponse]
    ) -> None: ...
    def clear_on_new_window(self) -> None: ...
    def set_drag_drop_listening(self, enabled: bool) -> None: ...
    def set_bounds(self, x: float, y: float, width: float, height: float) -> None: ...
    def set_visible(self, visible: bool) -> None: ...
    def set_background_color(self, r: int, g: int, b: int, a: int) -> None: ...
    def set_mac_web_input_active(self, active: bool) -> None: ...
    def set_mac_wakeup_write_fd(self, fd: int) -> None: ...
    def take_mac_tk_unfocus(self) -> bool: ...
    def mac_tk_unfocus_pending(self) -> bool: ...
    def mac_request_tk_unfocus(self) -> None: ...
    def mac_web_input_active(self) -> bool: ...
    def mac_hit_test_wry_point(self, x: float, y: float) -> bool: ...
    def focus(self) -> None: ...
    def focus_parent(self) -> None: ...
    def open_devtools(self) -> None: ...
    def close_devtools(self) -> None: ...
    def is_devtools_open(self) -> bool: ...
    def url(self) -> str | None: ...
    def is_alive(self) -> bool: ...
    def destroy(self) -> None: ...
    def force_destroy(self) -> None: ...

def pump_events(max_iterations: int | None = None) -> bool: ...
def ensure_gtk_init() -> None: ...
def disable_macos_automatic_window_tabbing() -> None: ...
def disable_macos_window_tabbing(parent: int) -> None: ...
