from collections.abc import Callable
from typing import Any, Final, final

__all__: Final = [
    "WebView",
    "WebSession",
    "NativeGcCompanion",
    "Cookie",
    "PageLoadEvent",
    "NewWindowResponse",
    "PermissionKind",
    "PermissionResponse",
    "DragDropEvent",
    "pump_events",
    "ensure_gtk_init",
    "configure_wakeup_write_fd",
    "disable_macos_automatic_window_tabbing",
    "disable_macos_window_tabbing",
]

@final
class PageLoadEvent:
    Started: PageLoadEvent
    Finished: PageLoadEvent

@final
class NewWindowResponse:
    Allow: NewWindowResponse
    Deny: NewWindowResponse

@final
class PermissionKind:
    Microphone: PermissionKind
    Camera: PermissionKind
    Geolocation: PermissionKind
    Notifications: PermissionKind
    ClipboardRead: PermissionKind
    DisplayCapture: PermissionKind
    Midi: PermissionKind
    Sensors: PermissionKind
    MediaKeySystemAccess: PermissionKind
    LocalFonts: PermissionKind
    WindowManagement: PermissionKind
    PointerLock: PermissionKind
    AutomaticDownloads: PermissionKind
    FileSystemAccess: PermissionKind
    Autoplay: PermissionKind
    Other: PermissionKind

@final
class PermissionResponse:
    Allow: PermissionResponse
    Deny: PermissionResponse
    Default: PermissionResponse

@final
class DragDropEvent:
    Enter: DragDropEvent
    Over: DragDropEvent
    Drop: DragDropEvent
    Leave: DragDropEvent
    Unknown: DragDropEvent

@final
class Cookie:
    def __new__(
        cls,
        name: str,
        value: str,
        *,
        domain: str | None = None,
        path: str | None = None,
        secure: bool | None = None,
        http_only: bool | None = None,
        same_site: str | None = None,
        max_age: float | None = None,
        expires: float | None = None,
    ) -> Cookie: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> str: ...
    @property
    def domain(self) -> str | None: ...
    @property
    def path(self) -> str | None: ...
    @property
    def secure(self) -> bool | None: ...
    @property
    def http_only(self) -> bool | None: ...
    @property
    def same_site(self) -> str | None: ...
    @property
    def max_age(self) -> float | None: ...
    @property
    def expires(self) -> float | None: ...

@final
class WebSession:
    def __new__(
        cls,
        *,
        data_directory: str | None = None,
        ephemeral: bool = False,
    ) -> WebSession: ...
    @property
    def data_directory(self) -> str | None: ...
    @property
    def ephemeral(self) -> bool: ...

@final
class NativeGcCompanion:
    def on_native_deallocated(self) -> None: ...
    def is_alive(self) -> bool: ...

@final
class WebView:
    def __new__(
        cls,
        parent: int,
        *,
        owner_thread: int | None = None,
        width: int = 800,
        height: int = 600,
        url: str | None = None,
        html: str | None = None,
        app_root: str | None = None,
        spa_fallback: bool = False,
        app_cache_control: str | None = None,
        app_csp: str | None = None,
        app_coop: bool = False,
        app_corp: bool = False,
        visible: bool = True,
        devtools: bool = False,
        clipboard: bool = False,
        javascript_enabled: bool = True,
        autoplay: bool = True,
        hotkeys_zoom: bool = False,
        back_forward_gestures: bool = False,
        default_context_menus: bool = True,
        https_scheme: bool = True,
        proxy: tuple[str, str, str] | None = None,
        focused: bool = True,
        background_color: tuple[int, int, int, int] | None = None,
        user_agent: str | None = None,
        initialization_script: str | None = None,
        on_navigation: Callable[[str], bool] | None = None,
        on_new_window: Callable[[str], NewWindowResponse] | None = None,
        on_permission: Callable[[PermissionKind], PermissionResponse] | None = None,
        page_load_listening: bool = False,
        ipc_listening: bool = False,
        title_listening: bool = False,
        drag_drop_listening: bool = False,
        on_download_started: (
            Callable[[str, str], tuple[bool, str | None]] | None
        ) = None,
        download_complete_listening: bool = False,
        with_ipc: bool = True,
        session: WebSession | None = None,
    ) -> WebView: ...
    def load_url(self, url: str) -> None: ...
    def load_url_with_headers(
        self, url: str, headers: list[tuple[str, str]]
    ) -> None: ...
    def load_html(self, html: str) -> None: ...
    def reload(self) -> None: ...
    def go_back(self) -> None: ...
    def go_forward(self) -> None: ...
    def can_go_back(self) -> bool: ...
    def can_go_forward(self) -> bool: ...
    def print(self) -> None: ...
    def print_with_options(
        self,
        *,
        top: float = 0.0,
        right: float = 0.0,
        bottom: float = 0.0,
        left: float = 0.0,
    ) -> None: ...
    def set_zoom(self, scale: float) -> None: ...
    def cookies(self) -> list[Cookie]: ...
    def cookies_for_url(self, url: str) -> list[Cookie]: ...
    def set_cookie(self, cookie: Cookie) -> None: ...
    def delete_cookie(self, cookie: Cookie) -> None: ...
    def clear_all_browsing_data(self) -> None: ...
    def eval_js(self, script: str) -> None: ...
    def eval_js_with_callback(
        self, script: str, callback: Callable[[str], Any]
    ) -> int: ...
    def drain_eval_callbacks(
        self,
    ) -> list[tuple[int, Callable[[str], Any], str | None]]: ...
    def drain_sync_hooks(self) -> None: ...
    def take_queue_drop_counts(self) -> tuple[int, int, int, int, int, int]: ...
    def take_queue_drop_stats(
        self,
    ) -> tuple[int, int, int, int, int, int, int]: ...
    def set_ipc_listening(self, enabled: bool) -> None: ...
    def set_on_navigation(self, handler: Callable[[str], bool]) -> None: ...
    def clear_on_navigation(self) -> None: ...
    def set_page_load_listening(self, enabled: bool) -> None: ...
    def drain_page_load_events(self) -> list[tuple[PageLoadEvent, str]]: ...
    def drain_rpc_messages(self) -> list[tuple[str, str]]: ...
    def drain_window_ipc_messages(self) -> list[tuple[str, str]]: ...
    def drain_ipc_messages(self) -> list[tuple[str, str]]: ...
    def drain_title_events(self) -> list[str]: ...
    def drain_drag_drop_events(
        self,
    ) -> list[tuple[DragDropEvent, list[str], tuple[int, int]]]: ...
    def set_on_download_started(
        self, handler: Callable[[str, str], tuple[bool, str | None]]
    ) -> None: ...
    def clear_on_download_started(self) -> None: ...
    def set_download_complete_listening(self, enabled: bool) -> None: ...
    def drain_download_complete_events(
        self,
    ) -> list[tuple[str, str | None, bool]]: ...
    def _enqueue_download_complete_event(
        self, url: str, dest: str | None, success: bool
    ) -> None: ...
    def _enqueue_ipc_message(
        self, message: str, source_url: str | None = None
    ) -> None: ...
    def _enqueue_title_event(self, title: str) -> None: ...
    def _enqueue_drag_drop_event(
        self,
        event: DragDropEvent,
        paths: list[str],
        position: tuple[int, int],
    ) -> None: ...
    def set_title_listening(self, enabled: bool) -> None: ...
    def set_on_new_window(
        self, handler: Callable[[str], NewWindowResponse]
    ) -> None: ...
    def clear_on_new_window(self) -> None: ...
    def set_drag_drop_listening(self, enabled: bool) -> None: ...
    def set_bounds(self, x: float, y: float, width: float, height: float) -> None: ...
    def bounds(self) -> tuple[float, float, float, float]: ...
    def set_visible(self, visible: bool) -> None: ...
    def set_background_color(self, r: int, g: int, b: int, a: int) -> None: ...
    def set_mac_web_input_active(self, active: bool) -> None: ...
    def set_mac_wakeup_write_fd(self, fd: int) -> None: ...
    def take_mac_tk_unfocus(self) -> bool: ...
    def mac_tk_unfocus_pending(self) -> bool: ...
    def mac_request_tk_unfocus(self) -> None: ...
    def mac_web_input_active(self) -> bool: ...
    def mac_hit_test_wry_point(self, x: float, y: float) -> bool: ...
    def focus(self) -> None: ...
    def focus_parent(self) -> None: ...
    def open_devtools(self) -> None: ...
    def close_devtools(self) -> None: ...
    def is_devtools_open(self) -> bool: ...
    def raise_to_front(self) -> None: ...
    def url(self) -> str | None: ...
    def is_alive(self) -> bool: ...
    def gc_companion(self) -> NativeGcCompanion: ...
    def destroy(self) -> None: ...
    def force_destroy(self) -> None: ...

def pump_events(max_iterations: int | None = None) -> bool: ...
def ensure_gtk_init() -> None: ...
def configure_wakeup_write_fd(fd: int) -> None: ...
def disable_macos_automatic_window_tabbing() -> None: ...
def disable_macos_window_tabbing(parent: int) -> None: ...
