from collections.abc import Callable
from typing import Any, Final, final

__all__: Final = [
    "WebView",
    "PageLoadEvent",
    "NewWindowResponse",
    "DragDropEvent",
    "pump_events",
    "ensure_gtk_init",
]

@final
class PageLoadEvent:
    Started: PageLoadEvent
    Finished: PageLoadEvent

@final
class NewWindowResponse:
    Allow: NewWindowResponse
    Deny: NewWindowResponse

@final
class DragDropEvent:
    Enter: DragDropEvent
    Over: DragDropEvent
    Drop: DragDropEvent
    Leave: DragDropEvent
    Unknown: DragDropEvent

@final
class WebView:
    def __new__(
        cls,
        parent: int,
        *,
        width: int = 800,
        height: int = 600,
        url: str | None = None,
        html: str | None = None,
        visible: bool = True,
        devtools: bool = False,
        focused: bool = True,
        background_color: tuple[int, int, int, int] | None = None,
        user_agent: str | None = None,
        initialization_script: str | None = None,
        ipc_handler: Callable[[str], Any] | None = None,
        on_navigation: Callable[[str], bool] | None = None,
        on_title_changed: Callable[[str], Any] | None = None,
        on_new_window: Callable[[str], NewWindowResponse] | None = None,
        drag_drop_handler: Callable[[DragDropEvent, list[str], tuple[int, int]], bool]
        | None = None,
    ) -> WebView: ...
    def load_url(self, url: str) -> None: ...
    def load_html(self, html: str) -> None: ...
    def reload(self) -> None: ...
    def eval_js(self, script: str) -> None: ...
    def eval_js_with_callback(
        self, script: str, callback: Callable[[str], Any]
    ) -> None: ...
    def set_ipc_handler(self, handler: Callable[[str], Any]) -> None: ...
    def clear_ipc_handler(self) -> None: ...
    def set_on_navigation(self, handler: Callable[[str], bool]) -> None: ...
    def clear_on_navigation(self) -> None: ...
    def drain_page_load_events(self) -> list[tuple[PageLoadEvent, str]]: ...
    def set_on_title_changed(self, handler: Callable[[str], Any]) -> None: ...
    def clear_on_title_changed(self) -> None: ...
    def set_on_new_window(
        self, handler: Callable[[str], NewWindowResponse]
    ) -> None: ...
    def clear_on_new_window(self) -> None: ...
    def set_drag_drop_handler(
        self,
        handler: Callable[[DragDropEvent, list[str], tuple[int, int]], bool],
    ) -> None: ...
    def clear_drag_drop_handler(self) -> None: ...
    def set_bounds(self, x: float, y: float, width: float, height: float) -> None: ...
    def set_visible(self, visible: bool) -> None: ...
    def set_background_color(self, r: int, g: int, b: int, a: int) -> None: ...
    def set_mac_web_input_active(self, active: bool) -> None: ...
    def set_mac_wakeup_write_fd(self, fd: int) -> None: ...
    def take_mac_tk_unfocus(self) -> bool: ...
    def mac_tk_unfocus_pending(self) -> bool: ...
    def mac_request_tk_unfocus(self) -> None: ...
    def mac_web_input_active(self) -> bool: ...
    def mac_hit_test_wry_point(self, x: float, y: float) -> bool: ...
    def focus(self) -> None: ...
    def focus_parent(self) -> None: ...
    def open_devtools(self) -> None: ...
    def close_devtools(self) -> None: ...
    def is_devtools_open(self) -> bool: ...
    def url(self) -> str | None: ...
    def destroy(self) -> None: ...

def pump_events() -> None: ...
def ensure_gtk_init() -> None: ...
